name: Test and Coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm install
        run: npm ci

      - name: Run tests and generate coverage
        run: npm run coverage

  coverage-report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm install
        run: npm ci

      - name: Install coverage tools
        run: npm install -g codecov

      - name: Upload coverage to Codecov
        run: codecov
