name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm install
        run: npm ci

      - name: Run tests and generate coverage report
        run: npm run test

      - name: Generate Coverage Badge
        run: |
          COVERAGE_BADGE_URL="https://codecov.io/gh/tarektarho/react-accordion/main/graph/badge.svg"
          BADGE_MARKDOWN="[![Test Coverage]($COVERAGE_BADGE_URL)](https://codecov.io/gh/tarektarho/react-accordion)"
          echo "$BADGE_MARKDOWN" > coverage-badge.md
        env:
          COVERAGE_BADGE_URL: "https://img.shields.io/codecov/c/github/tarektarho/react-accordion/main"

      - name: Upload Badge Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage-badge.md
