name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build

      - name: Run tests and calculate coverage
        run: npm run test -- --coverage

  generate-badge:
    runs-on: ubuntu-latest
    needs: build-and-test

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm install
        run: npm ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate Codecov badge
        run: |
          COVERAGE_BADGE_URL="https://img.shields.io/codecov/c/github/${{ github.repository }}/main"
          echo "[![Codecov branch]($COVERAGE_BADGE_URL)]($COVERAGE_BADGE_URL)" >> coverage-badge.md
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add coverage-badge.md
          git commit -m "Add Codecov coverage badge [add coverage-badge.md]"
          git push
        env:
          COVERAGE_BADGE_URL: "https://img.shields.io/codecov/c/github/tarektarho/react-accordion/main"

      - name: Get badge URL
        id: generate-badge
        run: echo "::set-output name=coverage_badge_url::$(cat coverage-badge.md)"
